# ARRAY OPERATIONS USING NUMPY

In [1]:
import numpy as np


In [27]:
a = np.random.randint(1,10,size=(3,3))
b = np.random.randint(1,10,size=(3,3))
c = np.random.randint(1,10,size=(2,3))

In [22]:
def add(m1,m2):
    if m1.shape == m2.shape:
        return m1+m2
    else:
        return None
    
def sub(m1,m2):
     if m1.shape == m2.shape:
        return m1-m2
     else:
        return None
def mul(m1,m2):
    if m1.shape[1] == m2.shape[0]:
        return m1 @ m2
    else:
        return None
        
def subset(m1,r1,r2,c1,c2):
    if r1 < m1.shape[0] and r1 > 0 and c1 >0 and c1 <m1.shape[1]:
        return m1[r1:r2,c1:c2]
    else:
        return m1

In [23]:
add(a,b)

array([[ 20, 109, 133],
       [ 44,  95, 192],
       [ 79, 102,  90]])

In [24]:
sub(a,b)

array([[  0,   7,  23],
       [ 22, -73,  -6],
       [-61,  60,   8]])

In [28]:
mul(a,b)

array([[75, 69, 75],
       [19, 17, 19],
       [60, 50, 50]])

In [29]:
mul(a,c)